version: 2

project_name: hytale-server-runner

before:
  hooks:
    - go mod tidy

builds:
  - id: hytale-server-runner
    main: .
    binary: hytale-server-runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/voidcubedotgg/hytale-server-runner/cmd.version={{ .Version }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
